In [1]:
import pandas as pd
import psycopg2
from sqlalchemy import create_engine
import logging

In [18]:

# Function to load and analyze data
def analyze_data(file_path):
    try:
        df = pd.read_csv(file_path)
        print(f"Data from {file_path}")
        print("\nHead of the DataFrame:")
        display(df.head())
        print("\nInfo of the DataFrame:")
        display(df.info())
        print("\nDescribe the DataFrame:")
        display(df.describe(include='all'))
    except Exception as e:
        print(f"Error processing file {file_path}: {e}")

# Analyze cheMed dataset
print("Analyzing cheMed dataset")
analyze_data('../telegram_data_scrapper/output/data/cheMed.csv')
print("="*80)

Analyzing cheMed dataset
Data from ../telegram_data_scrapper/output/data/cheMed.csv

Head of the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
0,msg_iteration.0.user.CheMed123.post.97,1627056354,CheMed123,97,"⚠️Notice!\nDear esteemed customers,\nDue to fo...","⚠️Notice! Dear esteemed customers, Due to four...",2023-02-10 12:23:06+00:00,https://t.me/CheMed123/97,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,msg_iteration.1.user.CheMed123.post.96,1627056354,CheMed123,96,Mela-One በውስጡ ሆርሞን ያለው ድንገተኛ ወሊድ መቆጣጠርያ ሲሆን ያለ...,Mela-One በውስጡ ሆርሞን ያለው ድንገተኛ ወሊድ መቆጣጠርያ ሲሆን ያለ...,2023-02-02 08:58:52+00:00,https://t.me/CheMed123/96,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,msg_iteration.2.user.CheMed123.post.95,1627056354,CheMed123,95,አዚትሮማይሲን በሃኪም መድሃኒት ማዘዣ ከሚታዘዙ አንቲባዮቲኮች አንዱ ሲሆን...,አዚትሮማይሲን በሃኪም መድሃኒት ማዘዣ ከሚታዘዙ አንቲባዮቲኮች አንዱ ሲሆን...,2023-02-01 08:59:37+00:00,https://t.me/CheMed123/95,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,msg_iteration.3.user.CheMed123.post.94,1627056354,CheMed123,94,Che-Med Trivia #3\n\nምግብና መጠጦች አንዳንድ መድሃኒቶች በደ...,Che-Med Trivia #3 ምግብና መጠጦች አንዳንድ መድሃኒቶች በደንብ ...,2023-01-31 09:19:53+00:00,https://t.me/CheMed123/94,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,msg_iteration.4.user.CheMed123.post.93,1627056354,CheMed123,93,"Che-Med Trivia #2\n\nእንደ Ciprofloxacin, Doxycy...","Che-Med Trivia #2 እንደ Ciprofloxacin, Doxycycli...",2023-01-30 09:45:25+00:00,https://t.me/CheMed123/93,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Info of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   signature                   72 non-null     object
 1   channel_id                  72 non-null     int64
 2   channel_name                72 non-null     object
 3   msg_id                      72 non-null     int64
 4   message                     63 non-null     object
 5   cleaned_message             63 non-null     object
 6   date                        72 non-null     object
 7   msg_link                    72 non-null     object
 8   msg_from_peer               0 non-null      float64
 9   msg_from_id                 0 non-null      float64
 10  views                       72 non-null     int64
 11  number_replies              72 non-null     int64
 12  number_forwards             72 non-null     int64
 13  is_forward                  72 non-null     int64
 14  forward_msg_from_peer_type  8 non-null      object
 15  forward_msg_from_peer_id    8 non-null      float64
 16  forward_msg_from_peer_name  0 non-null      float64
 17  forward_msg_date            8 non-null      object
 18  forward_msg_date_string     8 non-null      object
 19  forward_msg_link            0 non-null      float64
 20  is_reply                    72 non-null     int64
 21  reply_to_msg_id             0 non-null      float64
 22  reply_msg_link              0 non-null      float64
 23  contains_media              72 non-null     int64
 24  media_type                  72 non-null     object
 25  has_url                     72 non-null     int64
 26  url                         2 non-null      object
 27  domain                      2 non-null      object
 28  url_title                   2 non-null      object
 29  url_description             2 non-null      object
 30  document_type               3 non-null      object
 31  document_id                 3 non-null      float64
 32  document_video_duration     3 non-null      float64
 33  document_filename           1 non-null      object
 34  poll_id                     0 non-null      float64
 35  poll_question               0 non-null      float64
 36  poll_total_voters           0 non-null      float64
 37  poll_results                0 non-null      float64
 38  contact_phone_number        0 non-null      float64
 39  contact_name                0 non-null      float64
 40  contact_userid              0 non-null      float64
 41  geo_type                    0 non-null      float64
 42  lat                         0 non-null      float64
 43  lng                         0 non-null      float64
 44  venue_id                    0 non-null      float64
 45  venue_type                  0 non-null      float64
 46  venue_title                 0 non-null      float64
 47  venue_address               0 non-null      float64
 48  venue_provider              0 non-null      float64
dtypes: float64(24), int64(9), object(16)
memory usage: 27.7+ KB

None

Describe the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
count,72,7.200000e+01,72,72.000000,63,63,72,72,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unique,72,NaN,1,NaN,59,59,72,72,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,msg_iteration.0.user.CheMed123.post.97,NaN,CheMed123,NaN,www.chemeds.org መድሀኒትዎን ለማግኘት ዘመናዊው መንገድ ነው፡፡ ...,www.chemeds.org መድሀኒትዎን ለማግኘት ዘመናዊው መንገድ ነው፡፡ ...,2023-02-10 12:23:06+00:00,https://t.me/CheMed123/97,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,72,NaN,2,2,1,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.627056e+09,NaN,52.222222,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,0.000000e+00,NaN,27.851327,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1.627056e+09,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,1.627056e+09,NaN,28.500000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1.627056e+09,NaN,51.500000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1.627056e+09,NaN,77.250000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.627056e+09,NaN,97.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================

In [20]:
# Analyze Doctorset dataset
print("Analyzing Doctorset dataset")
analyze_data('../telegram_data_scrapper/output/data/Doctorset.csv')
print("="*80)

Analyzing Doctorset dataset
Data from ../telegram_data_scrapper/output/data/Doctorset.csv

Head of the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
0,msg_iteration.0.user.DoctorsET.post.864,1102021238,DoctorsET,864,https://youtu.be/5DBoEm-8kmA?si=LDLuEecNfULJVD...,https://youtu.be/5DBoEm-8kmA?si=LDLuEecNfULJVD...,2023-12-18 17:04:02+00:00,https://t.me/DoctorsET/864,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,msg_iteration.1.user.DoctorsET.post.863,1102021238,DoctorsET,863,ዶክተርስ ኢትዮጵያ በ አዲስ አቀራረብ በ ቴሌቪዥን ፕሮግራሙን ለመጀመር ከ...,ዶክተርስ ኢትዮጵያ በ አዲስ አቀራረብ በ ቴሌቪዥን ፕሮግራሙን ለመጀመር ከ...,2023-11-03 16:14:39+00:00,https://t.me/DoctorsET/863,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,msg_iteration.2.user.DoctorsET.post.862,1102021238,DoctorsET,862,ሞት በስኳር \n\nለልጆቻችን የምናሲዘው ምሳቃ ሳናቀው እድሚያቸውን ይቀን...,ሞት በስኳር ለልጆቻችን የምናሲዘው ምሳቃ ሳናቀው እድሚያቸውን ይቀንሰው ይ...,2023-10-02 16:37:39+00:00,https://t.me/DoctorsET/862,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,msg_iteration.3.user.DoctorsET.post.861,1102021238,DoctorsET,861,ከ HIV የተፈወሰ ሰው አጋጥሟችሁ ያቃል ? ፈውስ እና ህክምና ?\n\nሙ...,ከ HIV የተፈወሰ ሰው አጋጥሟችሁ ያቃል ? ፈውስ እና ህክምና ? ሙሉ ቪ...,2023-09-16 07:54:32+00:00,https://t.me/DoctorsET/861,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,msg_iteration.4.user.DoctorsET.post.860,1102021238,DoctorsET,860,በቅርብ ጊዜ በሃገራችን ላይ እየተስተዋለ ያለ የተመሳሳይ ፆታ ( Homos...,በቅርብ ጊዜ በሃገራችን ላይ እየተስተዋለ ያለ የተመሳሳይ ፆታ ( Homos...,2023-09-01 16:16:15+00:00,https://t.me/DoctorsET/860,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Info of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   signature                   756 non-null    object
 1   channel_id                  756 non-null    int64
 2   channel_name                756 non-null    object
 3   msg_id                      756 non-null    int64
 4   message                     605 non-null    object
 5   cleaned_message             605 non-null    object
 6   date                        756 non-null    object
 7   msg_link                    756 non-null    object
 8   msg_from_peer               0 non-null      float64
 9   msg_from_id                 0 non-null      float64
 10  views                       756 non-null    int64
 11  number_replies              756 non-null    int64
 12  number_forwards             756 non-null    int64
 13  is_forward                  756 non-null    int64
 14  forward_msg_from_peer_type  7 non-null      object
 15  forward_msg_from_peer_id    7 non-null      float64
 16  forward_msg_from_peer_name  5 non-null      object
 17  forward_msg_date            7 non-null      object
 18  forward_msg_date_string     7 non-null      object
 19  forward_msg_link            5 non-null      object
 20  is_reply                    756 non-null    int64
 21  reply_to_msg_id             0 non-null      float64
 22  reply_msg_link              0 non-null      float64
 23  contains_media              756 non-null    int64
 24  media_type                  610 non-null    object
 25  has_url                     756 non-null    int64
 26  url                         157 non-null    object
 27  domain                      157 non-null    object
 28  url_title                   156 non-null    object
 29  url_description             150 non-null    object
 30  document_type               47 non-null     object
 31  document_id                 47 non-null     float64
 32  document_video_duration     26 non-null     float64
 33  document_filename           21 non-null     object
 34  poll_id                     0 non-null      float64
 35  poll_question               0 non-null      float64
 36  poll_total_voters           0 non-null      float64
 37  poll_results                0 non-null      float64
 38  contact_phone_number        0 non-null      float64
 39  contact_name                0 non-null      float64
 40  contact_userid              0 non-null      float64
 41  geo_type                    0 non-null      float64
 42  lat                         0 non-null      float64
 43  lng                         0 non-null      float64
 44  venue_id                    0 non-null      float64
 45  venue_type                  0 non-null      float64
 46  venue_title                 0 non-null      float64
 47  venue_address               0 non-null      float64
 48  venue_provider              0 non-null      float64
dtypes: float64(22), int64(9), object(18)
memory usage: 289.5+ KB

None

Describe the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
count,756,7.560000e+02,756,756.000000,605,605,756,756,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unique,756,NaN,1,NaN,591,591,696,756,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,msg_iteration.0.user.DoctorsET.post.864,NaN,DoctorsET,NaN,#Dailytips \n#DOCTORSETHIOPIA,#Dailytips #DOCTORSETHIOPIA,2022-02-04 18:22:07+00:00,https://t.me/DoctorsET/864,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,756,NaN,7,7,9,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.102021e+09,NaN,434.621693,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,0.000000e+00,NaN,249.208575,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1.102021e+09,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,1.102021e+09,NaN,218.750000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1.102021e+09,NaN,435.500000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1.102021e+09,NaN,655.250000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.102021e+09,NaN,864.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================

In [21]:
# Analyze EAHCI dataset
print("Analyzing EAHCI dataset")
analyze_data('../telegram_data_scrapper/output/data/EAHCI.csv')
print("="*80)

Analyzing EAHCI dataset
Data from ../telegram_data_scrapper/output/data/EAHCI.csv

Head of the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
0,msg_iteration.0.user.EAHCI.post.2156,1432982009,EAHCI,2156,💥የሞያ ፈቃድ በቅርቡ ለምታሳድሱ💥 \n\n#CPD_(...,💥የሞያ ፈቃድ በቅርቡ ለምታሳድሱ💥 #CPD_(+Online ) #ሰኔ 7 /2...,2024-06-12 05:44:23+00:00,https://t.me/EAHCI/2156,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,msg_iteration.1.user.EAHCI.post.2155,1432982009,EAHCI,2155,NaN,NaN,2024-06-11 17:26:32+00:00,https://t.me/EAHCI/2155,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,msg_iteration.2.user.EAHCI.post.2154,1432982009,EAHCI,2154,#💥የግርዛት_ስልጠና_Addis_Ababa & nekemte\n#Circumcis...,#💥የግርዛት_ስልጠና_Addis_Ababa & nekemte #Circumcisi...,2024-06-11 17:26:32+00:00,https://t.me/EAHCI/2154,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,msg_iteration.3.user.EAHCI.post.2152,1432982009,EAHCI,2152,#💥የግርዛት_ስልጠና_Addis_Ababa\n#Circumcision_Skill_...,#💥የግርዛት_ስልጠና_Addis_Ababa #Circumcision_Skill_T...,2024-06-10 14:41:34+00:00,https://t.me/EAHCI/2152,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,msg_iteration.4.user.EAHCI.post.2151,1432982009,EAHCI,2151,#💥የግርዛት_ስልጠና_Addis_Ababa\n#Circumcision_Skill_...,#💥የግርዛት_ስልጠና_Addis_Ababa #Circumcision_Skill_T...,2024-06-10 14:41:34+00:00,https://t.me/EAHCI/2151,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Info of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1637 entries, 0 to 1636
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   signature                   1637 non-null   object
 1   channel_id                  1637 non-null   int64
 2   channel_name                1637 non-null   object
 3   msg_id                      1637 non-null   int64
 4   message                     1374 non-null   object
 5   cleaned_message             1374 non-null   object
 6   date                        1637 non-null   object
 7   msg_link                    1637 non-null   object
 8   msg_from_peer               0 non-null      float64
 9   msg_from_id                 0 non-null      float64
 10  views                       1637 non-null   int64
 11  number_replies              1637 non-null   int64
 12  number_forwards             1637 non-null   int64
 13  is_forward                  1637 non-null   int64
 14  forward_msg_from_peer_type  251 non-null    object
 15  forward_msg_from_peer_id    251 non-null    float64
 16  forward_msg_from_peer_name  251 non-null    object
 17  forward_msg_date            258 non-null    object
 18  forward_msg_date_string     258 non-null    object
 19  forward_msg_link            251 non-null    object
 20  is_reply                    1637 non-null   int64
 21  reply_to_msg_id             0 non-null      float64
 22  reply_msg_link              0 non-null      float64
 23  contains_media              1637 non-null   int64
 24  media_type                  1460 non-null   object
 25  has_url                     1637 non-null   int64
 26  url                         113 non-null    object
 27  domain                      113 non-null    object
 28  url_title                   113 non-null    object
 29  url_description             113 non-null    object
 30  document_type               71 non-null     object
 31  document_id                 71 non-null     float64
 32  document_video_duration     11 non-null     float64
 33  document_filename           60 non-null     object
 34  poll_id                     0 non-null      float64
 35  poll_question               0 non-null      float64
 36  poll_total_voters           0 non-null      float64
 37  poll_results                0 non-null      float64
 38  contact_phone_number        0 non-null      float64
 39  contact_name                0 non-null      float64
 40  contact_userid              0 non-null      float64
 41  geo_type                    0 non-null      float64
 42  lat                         0 non-null      float64
 43  lng                         0 non-null      float64
 44  venue_id                    0 non-null      float64
 45  venue_type                  0 non-null      float64
 46  venue_title                 0 non-null      float64
 47  venue_address               0 non-null      float64
 48  venue_provider              0 non-null      float64
dtypes: float64(22), int64(9), object(18)
memory usage: 626.8+ KB

None

Describe the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
count,1637,1.637000e+03,1637,1637.000000,1374,1374,1637,1637,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unique,1637,NaN,1,NaN,1157,1146,1481,1637,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,msg_iteration.0.user.EAHCI.post.2156,NaN,EAHCI,NaN,➥ሀሙስ ይጀምራል-CPD-Pain Management Training \n(Eth...,#ነገ ይጀምራል #CPD ✔️#Title_Antimicrobial Drug Res...,2022-09-28 11:23:32+00:00,https://t.me/EAHCI/2156,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,1637,NaN,3,3,10,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.432982e+09,NaN,1115.980452,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,0.000000e+00,NaN,612.450601,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1.432982e+09,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,1.432982e+09,NaN,598.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1.432982e+09,NaN,1101.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1.432982e+09,NaN,1653.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.432982e+09,NaN,2156.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================

In [22]:
# Analyze EAHCI dataset
print("Analyzing EAHCI dataset")
analyze_data('../telegram_data_scrapper/output/data/EAHCI.csv')
print("="*80)

Analyzing EAHCI dataset
Data from ../telegram_data_scrapper/output/data/EAHCI.csv

Head of the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
0,msg_iteration.0.user.EAHCI.post.2156,1432982009,EAHCI,2156,💥የሞያ ፈቃድ በቅርቡ ለምታሳድሱ💥 \n\n#CPD_(...,💥የሞያ ፈቃድ በቅርቡ ለምታሳድሱ💥 #CPD_(+Online ) #ሰኔ 7 /2...,2024-06-12 05:44:23+00:00,https://t.me/EAHCI/2156,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,msg_iteration.1.user.EAHCI.post.2155,1432982009,EAHCI,2155,NaN,NaN,2024-06-11 17:26:32+00:00,https://t.me/EAHCI/2155,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,msg_iteration.2.user.EAHCI.post.2154,1432982009,EAHCI,2154,#💥የግርዛት_ስልጠና_Addis_Ababa & nekemte\n#Circumcis...,#💥የግርዛት_ስልጠና_Addis_Ababa & nekemte #Circumcisi...,2024-06-11 17:26:32+00:00,https://t.me/EAHCI/2154,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,msg_iteration.3.user.EAHCI.post.2152,1432982009,EAHCI,2152,#💥የግርዛት_ስልጠና_Addis_Ababa\n#Circumcision_Skill_...,#💥የግርዛት_ስልጠና_Addis_Ababa #Circumcision_Skill_T...,2024-06-10 14:41:34+00:00,https://t.me/EAHCI/2152,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,msg_iteration.4.user.EAHCI.post.2151,1432982009,EAHCI,2151,#💥የግርዛት_ስልጠና_Addis_Ababa\n#Circumcision_Skill_...,#💥የግርዛት_ስልጠና_Addis_Ababa #Circumcision_Skill_T...,2024-06-10 14:41:34+00:00,https://t.me/EAHCI/2151,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Info of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1637 entries, 0 to 1636
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   signature                   1637 non-null   object
 1   channel_id                  1637 non-null   int64
 2   channel_name                1637 non-null   object
 3   msg_id                      1637 non-null   int64
 4   message                     1374 non-null   object
 5   cleaned_message             1374 non-null   object
 6   date                        1637 non-null   object
 7   msg_link                    1637 non-null   object
 8   msg_from_peer               0 non-null      float64
 9   msg_from_id                 0 non-null      float64
 10  views                       1637 non-null   int64
 11  number_replies              1637 non-null   int64
 12  number_forwards             1637 non-null   int64
 13  is_forward                  1637 non-null   int64
 14  forward_msg_from_peer_type  251 non-null    object
 15  forward_msg_from_peer_id    251 non-null    float64
 16  forward_msg_from_peer_name  251 non-null    object
 17  forward_msg_date            258 non-null    object
 18  forward_msg_date_string     258 non-null    object
 19  forward_msg_link            251 non-null    object
 20  is_reply                    1637 non-null   int64
 21  reply_to_msg_id             0 non-null      float64
 22  reply_msg_link              0 non-null      float64
 23  contains_media              1637 non-null   int64
 24  media_type                  1460 non-null   object
 25  has_url                     1637 non-null   int64
 26  url                         113 non-null    object
 27  domain                      113 non-null    object
 28  url_title                   113 non-null    object
 29  url_description             113 non-null    object
 30  document_type               71 non-null     object
 31  document_id                 71 non-null     float64
 32  document_video_duration     11 non-null     float64
 33  document_filename           60 non-null     object
 34  poll_id                     0 non-null      float64
 35  poll_question               0 non-null      float64
 36  poll_total_voters           0 non-null      float64
 37  poll_results                0 non-null      float64
 38  contact_phone_number        0 non-null      float64
 39  contact_name                0 non-null      float64
 40  contact_userid              0 non-null      float64
 41  geo_type                    0 non-null      float64
 42  lat                         0 non-null      float64
 43  lng                         0 non-null      float64
 44  venue_id                    0 non-null      float64
 45  venue_type                  0 non-null      float64
 46  venue_title                 0 non-null      float64
 47  venue_address               0 non-null      float64
 48  venue_provider              0 non-null      float64
dtypes: float64(22), int64(9), object(18)
memory usage: 626.8+ KB

None

Describe the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
count,1637,1.637000e+03,1637,1637.000000,1374,1374,1637,1637,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unique,1637,NaN,1,NaN,1157,1146,1481,1637,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,msg_iteration.0.user.EAHCI.post.2156,NaN,EAHCI,NaN,➥ሀሙስ ይጀምራል-CPD-Pain Management Training \n(Eth...,#ነገ ይጀምራል #CPD ✔️#Title_Antimicrobial Drug Res...,2022-09-28 11:23:32+00:00,https://t.me/EAHCI/2156,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,1637,NaN,3,3,10,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.432982e+09,NaN,1115.980452,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,0.000000e+00,NaN,612.450601,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1.432982e+09,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,1.432982e+09,NaN,598.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1.432982e+09,NaN,1101.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1.432982e+09,NaN,1653.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.432982e+09,NaN,2156.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================

In [23]:
# Analyze EAHCI dataset
print("Analyzing EAHCI dataset")
analyze_data('../telegram_data_scrapper/output/data/EAHCI.csv')
print("="*80)

Analyzing EAHCI dataset
Data from ../telegram_data_scrapper/output/data/EAHCI.csv

Head of the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
0,msg_iteration.0.user.EAHCI.post.2156,1432982009,EAHCI,2156,💥የሞያ ፈቃድ በቅርቡ ለምታሳድሱ💥 \n\n#CPD_(...,💥የሞያ ፈቃድ በቅርቡ ለምታሳድሱ💥 #CPD_(+Online ) #ሰኔ 7 /2...,2024-06-12 05:44:23+00:00,https://t.me/EAHCI/2156,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,msg_iteration.1.user.EAHCI.post.2155,1432982009,EAHCI,2155,NaN,NaN,2024-06-11 17:26:32+00:00,https://t.me/EAHCI/2155,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,msg_iteration.2.user.EAHCI.post.2154,1432982009,EAHCI,2154,#💥የግርዛት_ስልጠና_Addis_Ababa & nekemte\n#Circumcis...,#💥የግርዛት_ስልጠና_Addis_Ababa & nekemte #Circumcisi...,2024-06-11 17:26:32+00:00,https://t.me/EAHCI/2154,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,msg_iteration.3.user.EAHCI.post.2152,1432982009,EAHCI,2152,#💥የግርዛት_ስልጠና_Addis_Ababa\n#Circumcision_Skill_...,#💥የግርዛት_ስልጠና_Addis_Ababa #Circumcision_Skill_T...,2024-06-10 14:41:34+00:00,https://t.me/EAHCI/2152,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,msg_iteration.4.user.EAHCI.post.2151,1432982009,EAHCI,2151,#💥የግርዛት_ስልጠና_Addis_Ababa\n#Circumcision_Skill_...,#💥የግርዛት_ስልጠና_Addis_Ababa #Circumcision_Skill_T...,2024-06-10 14:41:34+00:00,https://t.me/EAHCI/2151,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Info of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1637 entries, 0 to 1636
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   signature                   1637 non-null   object
 1   channel_id                  1637 non-null   int64
 2   channel_name                1637 non-null   object
 3   msg_id                      1637 non-null   int64
 4   message                     1374 non-null   object
 5   cleaned_message             1374 non-null   object
 6   date                        1637 non-null   object
 7   msg_link                    1637 non-null   object
 8   msg_from_peer               0 non-null      float64
 9   msg_from_id                 0 non-null      float64
 10  views                       1637 non-null   int64
 11  number_replies              1637 non-null   int64
 12  number_forwards             1637 non-null   int64
 13  is_forward                  1637 non-null   int64
 14  forward_msg_from_peer_type  251 non-null    object
 15  forward_msg_from_peer_id    251 non-null    float64
 16  forward_msg_from_peer_name  251 non-null    object
 17  forward_msg_date            258 non-null    object
 18  forward_msg_date_string     258 non-null    object
 19  forward_msg_link            251 non-null    object
 20  is_reply                    1637 non-null   int64
 21  reply_to_msg_id             0 non-null      float64
 22  reply_msg_link              0 non-null      float64
 23  contains_media              1637 non-null   int64
 24  media_type                  1460 non-null   object
 25  has_url                     1637 non-null   int64
 26  url                         113 non-null    object
 27  domain                      113 non-null    object
 28  url_title                   113 non-null    object
 29  url_description             113 non-null    object
 30  document_type               71 non-null     object
 31  document_id                 71 non-null     float64
 32  document_video_duration     11 non-null     float64
 33  document_filename           60 non-null     object
 34  poll_id                     0 non-null      float64
 35  poll_question               0 non-null      float64
 36  poll_total_voters           0 non-null      float64
 37  poll_results                0 non-null      float64
 38  contact_phone_number        0 non-null      float64
 39  contact_name                0 non-null      float64
 40  contact_userid              0 non-null      float64
 41  geo_type                    0 non-null      float64
 42  lat                         0 non-null      float64
 43  lng                         0 non-null      float64
 44  venue_id                    0 non-null      float64
 45  venue_type                  0 non-null      float64
 46  venue_title                 0 non-null      float64
 47  venue_address               0 non-null      float64
 48  venue_provider              0 non-null      float64
dtypes: float64(22), int64(9), object(18)
memory usage: 626.8+ KB

None

Describe the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
count,1637,1.637000e+03,1637,1637.000000,1374,1374,1637,1637,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unique,1637,NaN,1,NaN,1157,1146,1481,1637,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,msg_iteration.0.user.EAHCI.post.2156,NaN,EAHCI,NaN,➥ሀሙስ ይጀምራል-CPD-Pain Management Training \n(Eth...,#ነገ ይጀምራል #CPD ✔️#Title_Antimicrobial Drug Res...,2022-09-28 11:23:32+00:00,https://t.me/EAHCI/2156,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,1637,NaN,3,3,10,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.432982e+09,NaN,1115.980452,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,0.000000e+00,NaN,612.450601,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1.432982e+09,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,1.432982e+09,NaN,598.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1.432982e+09,NaN,1101.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1.432982e+09,NaN,1653.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.432982e+09,NaN,2156.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================

In [24]:
# Analyze lobelia4cosmetics dataset
print("Analyzing lobelia4cosmetics dataset")
analyze_data('../telegram_data_scrapper/output/data/lobelia4cosmetics.csv')
print("="*80)

Analyzing lobelia4cosmetics dataset
Data from ../telegram_data_scrapper/output/data/lobelia4cosmetics.csv

Head of the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
0,msg_iteration.0.user.lobelia4cosmetics.post.9437,1666492664,lobelia4cosmetics,9437,CENTRUM ADULT 50+ 200 GUMMIES \nPrice 5700 bir...,CENTRUM ADULT 50+ 200 GUMMIES Price 5700 birr ...,2024-06-12 08:36:35+00:00,https://t.me/lobelia4cosmetics/9437,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,msg_iteration.1.user.lobelia4cosmetics.post.9436,1666492664,lobelia4cosmetics,9436,OMEGA 3 200 SOFTGELS \nPrice 5000 birr \nTeleg...,OMEGA 3 200 SOFTGELS Price 5000 birr Telegram ...,2024-06-12 08:32:43+00:00,https://t.me/lobelia4cosmetics/9436,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,msg_iteration.2.user.lobelia4cosmetics.post.9435,1666492664,lobelia4cosmetics,9435,"OMEGA 3,6,9 150 SOFTGELS \nPrice 5000 birr \nT...","OMEGA 3,6,9 150 SOFTGELS Price 5000 birr Teleg...",2024-06-12 08:31:20+00:00,https://t.me/lobelia4cosmetics/9435,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,msg_iteration.3.user.lobelia4cosmetics.post.9434,1666492664,lobelia4cosmetics,9434,CENTRUM MEN 50+\nPrice 5700 birr \nTelegram ht...,CENTRUM MEN 50+ Price 5700 birr Telegram https...,2024-06-12 08:29:41+00:00,https://t.me/lobelia4cosmetics/9434,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,msg_iteration.4.user.lobelia4cosmetics.post.9433,1666492664,lobelia4cosmetics,9433,CENTRUM WOMEN 50+\nPrice 5700 birr \nTelegram ...,CENTRUM WOMEN 50+ Price 5700 birr Telegram htt...,2024-06-12 08:29:05+00:00,https://t.me/lobelia4cosmetics/9433,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Info of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3327 entries, 0 to 3326
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   signature                   3327 non-null   object
 1   channel_id                  3327 non-null   int64
 2   channel_name                3327 non-null   object
 3   msg_id                      3327 non-null   int64
 4   message                     2967 non-null   object
 5   cleaned_message             2967 non-null   object
 6   date                        3327 non-null   object
 7   msg_link                    3327 non-null   object
 8   msg_from_peer               0 non-null      float64
 9   msg_from_id                 0 non-null      float64
 10  views                       3327 non-null   int64
 11  number_replies              3327 non-null   int64
 12  number_forwards             3327 non-null   int64
 13  is_forward                  3327 non-null   int64
 14  forward_msg_from_peer_type  4 non-null      object
 15  forward_msg_from_peer_id    4 non-null      float64
 16  forward_msg_from_peer_name  4 non-null      object
 17  forward_msg_date            4 non-null      object
 18  forward_msg_date_string     4 non-null      object
 19  forward_msg_link            4 non-null      object
 20  is_reply                    3327 non-null   int64
 21  reply_to_msg_id             9 non-null      float64
 22  reply_msg_link              9 non-null      object
 23  contains_media              3327 non-null   int64
 24  media_type                  3327 non-null   object
 25  has_url                     3327 non-null   int64
 26  url                         2 non-null      object
 27  domain                      2 non-null      object
 28  url_title                   2 non-null      object
 29  url_description             2 non-null      object
 30  document_type               1 non-null      object
 31  document_id                 1 non-null      float64
 32  document_video_duration     0 non-null      float64
 33  document_filename           1 non-null      object
 34  poll_id                     0 non-null      float64
 35  poll_question               0 non-null      float64
 36  poll_total_voters           0 non-null      float64
 37  poll_results                0 non-null      float64
 38  contact_phone_number        0 non-null      float64
 39  contact_name                0 non-null      float64
 40  contact_userid              0 non-null      float64
 41  geo_type                    0 non-null      float64
 42  lat                         0 non-null      float64
 43  lng                         0 non-null      float64
 44  venue_id                    0 non-null      float64
 45  venue_type                  0 non-null      float64
 46  venue_title                 0 non-null      float64
 47  venue_address               0 non-null      float64
 48  venue_provider              0 non-null      float64
dtypes: float64(21), int64(9), object(19)
memory usage: 1.2+ MB

None

Describe the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
count,3327,3.327000e+03,3327,3327.000000,2967,2967,3327,3327,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unique,3327,NaN,1,NaN,821,806,1933,3327,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,msg_iteration.0.user.lobelia4cosmetics.post.9437,NaN,lobelia4cosmetics,NaN,Price 1800 birr \nTelegram https://t.me/lobeli...,Price 1800 birr Telegram https://t.me/lobelia4...,2024-04-30 07:18:14+00:00,https://t.me/lobelia4cosmetics/9437,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,3327,NaN,58,58,15,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.666493e+09,NaN,3950.870153,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,0.000000e+00,NaN,3569.197818,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1.666493e+09,NaN,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,1.666493e+09,NaN,1122.500000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1.666493e+09,NaN,2050.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1.666493e+09,NaN,8566.500000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.666493e+09,NaN,9437.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================

In [25]:
# Analyze EAHCI dataset
print("Analyzing EAHCI dataset")
analyze_data('../telegram_data_scrapper/output/data/EAHCI.csv')
print("="*80)

Analyzing EAHCI dataset
Data from ../telegram_data_scrapper/output/data/EAHCI.csv

Head of the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
0,msg_iteration.0.user.EAHCI.post.2156,1432982009,EAHCI,2156,💥የሞያ ፈቃድ በቅርቡ ለምታሳድሱ💥 \n\n#CPD_(...,💥የሞያ ፈቃድ በቅርቡ ለምታሳድሱ💥 #CPD_(+Online ) #ሰኔ 7 /2...,2024-06-12 05:44:23+00:00,https://t.me/EAHCI/2156,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,msg_iteration.1.user.EAHCI.post.2155,1432982009,EAHCI,2155,NaN,NaN,2024-06-11 17:26:32+00:00,https://t.me/EAHCI/2155,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,msg_iteration.2.user.EAHCI.post.2154,1432982009,EAHCI,2154,#💥የግርዛት_ስልጠና_Addis_Ababa & nekemte\n#Circumcis...,#💥የግርዛት_ስልጠና_Addis_Ababa & nekemte #Circumcisi...,2024-06-11 17:26:32+00:00,https://t.me/EAHCI/2154,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,msg_iteration.3.user.EAHCI.post.2152,1432982009,EAHCI,2152,#💥የግርዛት_ስልጠና_Addis_Ababa\n#Circumcision_Skill_...,#💥የግርዛት_ስልጠና_Addis_Ababa #Circumcision_Skill_T...,2024-06-10 14:41:34+00:00,https://t.me/EAHCI/2152,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,msg_iteration.4.user.EAHCI.post.2151,1432982009,EAHCI,2151,#💥የግርዛት_ስልጠና_Addis_Ababa\n#Circumcision_Skill_...,#💥የግርዛት_ስልጠና_Addis_Ababa #Circumcision_Skill_T...,2024-06-10 14:41:34+00:00,https://t.me/EAHCI/2151,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Info of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1637 entries, 0 to 1636
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   signature                   1637 non-null   object
 1   channel_id                  1637 non-null   int64
 2   channel_name                1637 non-null   object
 3   msg_id                      1637 non-null   int64
 4   message                     1374 non-null   object
 5   cleaned_message             1374 non-null   object
 6   date                        1637 non-null   object
 7   msg_link                    1637 non-null   object
 8   msg_from_peer               0 non-null      float64
 9   msg_from_id                 0 non-null      float64
 10  views                       1637 non-null   int64
 11  number_replies              1637 non-null   int64
 12  number_forwards             1637 non-null   int64
 13  is_forward                  1637 non-null   int64
 14  forward_msg_from_peer_type  251 non-null    object
 15  forward_msg_from_peer_id    251 non-null    float64
 16  forward_msg_from_peer_name  251 non-null    object
 17  forward_msg_date            258 non-null    object
 18  forward_msg_date_string     258 non-null    object
 19  forward_msg_link            251 non-null    object
 20  is_reply                    1637 non-null   int64
 21  reply_to_msg_id             0 non-null      float64
 22  reply_msg_link              0 non-null      float64
 23  contains_media              1637 non-null   int64
 24  media_type                  1460 non-null   object
 25  has_url                     1637 non-null   int64
 26  url                         113 non-null    object
 27  domain                      113 non-null    object
 28  url_title                   113 non-null    object
 29  url_description             113 non-null    object
 30  document_type               71 non-null     object
 31  document_id                 71 non-null     float64
 32  document_video_duration     11 non-null     float64
 33  document_filename           60 non-null     object
 34  poll_id                     0 non-null      float64
 35  poll_question               0 non-null      float64
 36  poll_total_voters           0 non-null      float64
 37  poll_results                0 non-null      float64
 38  contact_phone_number        0 non-null      float64
 39  contact_name                0 non-null      float64
 40  contact_userid              0 non-null      float64
 41  geo_type                    0 non-null      float64
 42  lat                         0 non-null      float64
 43  lng                         0 non-null      float64
 44  venue_id                    0 non-null      float64
 45  venue_type                  0 non-null      float64
 46  venue_title                 0 non-null      float64
 47  venue_address               0 non-null      float64
 48  venue_provider              0 non-null      float64
dtypes: float64(22), int64(9), object(18)
memory usage: 626.8+ KB

None

Describe the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
count,1637,1.637000e+03,1637,1637.000000,1374,1374,1637,1637,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unique,1637,NaN,1,NaN,1157,1146,1481,1637,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,msg_iteration.0.user.EAHCI.post.2156,NaN,EAHCI,NaN,➥ሀሙስ ይጀምራል-CPD-Pain Management Training \n(Eth...,#ነገ ይጀምራል #CPD ✔️#Title_Antimicrobial Drug Res...,2022-09-28 11:23:32+00:00,https://t.me/EAHCI/2156,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,1637,NaN,3,3,10,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.432982e+09,NaN,1115.980452,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,0.000000e+00,NaN,612.450601,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1.432982e+09,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,1.432982e+09,NaN,598.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1.432982e+09,NaN,1101.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1.432982e+09,NaN,1653.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.432982e+09,NaN,2156.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================

In [26]:
# Analyze yetenaweg dataset
print("Analyzing yetenaweg dataset")
analyze_data('../telegram_data_scrapper/output/data/yetenaweg.csv')
print("="*80)

Analyzing yetenaweg dataset
Data from ../telegram_data_scrapper/output/data/yetenaweg.csv

Head of the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
0,msg_iteration.1.user.yetenaweg.post.1082,1447066276,yetenaweg,1082,ጥያቄያችሁን አጋሩን,ጥያቄያችሁን አጋሩን,2024-06-09 15:28:37+00:00,https://t.me/yetenaweg/1082,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,msg_iteration.2.user.yetenaweg.post.1081,1447066276,yetenaweg,1081,https://t.me/yetenaweg?livestream\n\nስለ ኩላሊት ጤ...,https://t.me/yetenaweg?livestream ስለ ኩላሊት ጤና ፣...,2024-06-09 15:05:18+00:00,https://t.me/yetenaweg/1081,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,msg_iteration.4.user.yetenaweg.post.1079,1447066276,yetenaweg,1079,NaN,NaN,2024-06-06 07:51:31+00:00,https://t.me/yetenaweg/1079,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,msg_iteration.5.user.yetenaweg.post.1078,1447066276,yetenaweg,1078,📣በዚህ እሁድ በቴሌግራም ቀጥታ ስርጭት የኩላሊት በሽታ ክትትል እና የዳያ...,📣በዚህ እሁድ በቴሌግራም ቀጥታ ስርጭት የኩላሊት በሽታ ክትትል እና የዳያ...,2024-06-06 07:51:30+00:00,https://t.me/yetenaweg/1078,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,msg_iteration.6.user.yetenaweg.post.1077,1447066276,yetenaweg,1077,https://www.clubhouse.com/room/xlOVk34E?utm_me...,https://www.clubhouse.com/room/xlOVk34E?utm_me...,2024-06-05 20:27:37+00:00,https://t.me/yetenaweg/1077,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Info of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 49 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   signature                   930 non-null    object
 1   channel_id                  930 non-null    int64
 2   channel_name                930 non-null    object
 3   msg_id                      930 non-null    int64
 4   message                     693 non-null    object
 5   cleaned_message             693 non-null    object
 6   date                        930 non-null    object
 7   msg_link                    930 non-null    object
 8   msg_from_peer               0 non-null      float64
 9   msg_from_id                 0 non-null      float64
 10  views                       930 non-null    int64
 11  number_replies              930 non-null    int64
 12  number_forwards             930 non-null    int64
 13  is_forward                  930 non-null    int64
 14  forward_msg_from_peer_type  71 non-null     object
 15  forward_msg_from_peer_id    71 non-null     float64
 16  forward_msg_from_peer_name  50 non-null     object
 17  forward_msg_date            129 non-null    object
 18  forward_msg_date_string     129 non-null    object
 19  forward_msg_link            50 non-null     object
 20  is_reply                    930 non-null    int64
 21  reply_to_msg_id             31 non-null     float64
 22  reply_msg_link              31 non-null     object
 23  contains_media              930 non-null    int64
 24  media_type                  831 non-null    object
 25  has_url                     930 non-null    int64
 26  url                         230 non-null    object
 27  domain                      230 non-null    object
 28  url_title                   225 non-null    object
 29  url_description             226 non-null    object
 30  document_type               57 non-null     object
 31  document_id                 57 non-null     float64
 32  document_video_duration     25 non-null     float64
 33  document_filename           37 non-null     object
 34  poll_id                     6 non-null      float64
 35  poll_question               6 non-null      object
 36  poll_total_voters           6 non-null      float64
 37  poll_results                6 non-null      object
 38  contact_phone_number        0 non-null      float64
 39  contact_name                0 non-null      float64
 40  contact_userid              0 non-null      float64
 41  geo_type                    0 non-null      float64
 42  lat                         0 non-null      float64
 43  lng                         0 non-null      float64
 44  venue_id                    0 non-null      float64
 45  venue_type                  0 non-null      float64
 46  venue_title                 0 non-null      float64
 47  venue_address               0 non-null      float64
 48  venue_provider              0 non-null      float64
dtypes: float64(19), int64(9), object(21)
memory usage: 356.1+ KB

None

Describe the DataFrame:

,signature,channel_id,channel_name,msg_id,message,cleaned_message,date,msg_link,msg_from_peer,msg_from_id,...,contact_name,contact_userid,geo_type,lat,lng,venue_id,venue_type,venue_title,venue_address,venue_provider
count,930,9.300000e+02,930,930.000000,693,693,930,930,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
unique,930,NaN,1,NaN,661,658,819,930,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,msg_iteration.1.user.yetenaweg.post.1082,NaN,yetenaweg,NaN,#የጤናወግንይጠይቁ\n\nበየካቲት 30/2015 ከሚከበረው የአለም የኩላሊት...,#የጤናወግንይጠይቁ በየካቲት 30/2015 ከሚከበረው የአለም የኩላሊት ቀን...,2020-03-18 10:57:45+00:00,https://t.me/yetenaweg/1082,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,930,NaN,8,8,12,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.447066e+09,NaN,525.921505,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,0.000000e+00,NaN,305.584043,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1.447066e+09,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,1.447066e+09,NaN,265.250000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1.447066e+09,NaN,522.500000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1.447066e+09,NaN,792.750000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.447066e+09,NaN,1082.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================

In [27]:
# Analyze imageoflobeli dataset
print("Analyzing imageoflobeli dataset")
analyze_data('imageoflobeli.csv')
print("="*80)

Analyzing imageoflobeli dataset
Data from imageoflobeli.csv

Head of the DataFrame:

,2.550000000000000000e+02,2.550000000000000000e+02.1,2.550000000000000000e+02.2,2.550000000000000000e+02.3,2.550000000000000000e+02.4,2.550000000000000000e+02.5,2.550000000000000000e+02.6,2.550000000000000000e+02.7,2.550000000000000000e+02.8,2.550000000000000000e+02.9,...,2.550000000000000000e+02.4245,2.550000000000000000e+02.4246,2.550000000000000000e+02.4247,2.550000000000000000e+02.4248,2.550000000000000000e+02.4249,2.550000000000000000e+02.4250,2.550000000000000000e+02.4251,2.550000000000000000e+02.4252,2.550000000000000000e+02.4253,2.550000000000000000e+02.4254
0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,...,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0
1,8.0,20.0,3.0,11.0,7.0,11.0,6.0,11.0,4.0,11.0,...,143.0,140.0,163.0,13.0,12.0,12.0,11.0,9.0,25.0,28.0
2,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,...,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0
3,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,...,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0
4,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,...,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0

Info of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Columns: 10000 entries, 2.550000000000000000e+02 to 2.550000000000000000e+02.4254
dtypes: float64(10000)
memory usage: 7.5 MB

None

Describe the DataFrame:

,2.550000000000000000e+02,2.550000000000000000e+02.1,2.550000000000000000e+02.2,2.550000000000000000e+02.3,2.550000000000000000e+02.4,2.550000000000000000e+02.5,2.550000000000000000e+02.6,2.550000000000000000e+02.7,2.550000000000000000e+02.8,2.550000000000000000e+02.9,...,2.550000000000000000e+02.4245,2.550000000000000000e+02.4246,2.550000000000000000e+02.4247,2.550000000000000000e+02.4248,2.550000000000000000e+02.4249,2.550000000000000000e+02.4250,2.550000000000000000e+02.4251,2.550000000000000000e+02.4252,2.550000000000000000e+02.4253,2.550000000000000000e+02.4254
count,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,...,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000
mean,220.204082,220.418367,220.040816,217.795918,217.846939,217.846939,217.928571,219.663265,218.836735,221.102041,...,224.326531,224.357143,223.234694,221.653061,221.704082,221.846939,221.979592,221.908163,222.132653,221.989796
std,83.078519,82.714878,83.073302,82.686710,82.758916,82.636498,82.669040,80.795012,81.344209,80.892507,...,76.750469,76.889833,77.728154,80.478095,80.393903,80.239635,80.136736,80.309207,79.841807,79.978154
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,254.000000,254.000000,253.000000,250.000000,250.000000,250.000000,250.000000,250.000000,249.750000,251.250000,...,254.000000,254.000000,254.000000,254.000000,254.000000,254.000000,254.000000,254.000000,254.000000,254.000000
50%,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,...,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000
75%,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,...,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000
max,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,...,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000

================================================================================